"""add is_deleted to product

Revision ID: 5124d093b266
Revises: abcea6b68cdd
Create Date: 2026-05-30 15:59:44.387771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5124d093b266'
down_revision: Union[str, Sequence[str], None] = 'abcea6b68cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('grand_total', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column(
    "products",
    sa.Column(
        "is_deleted",
        sa.Boolean(),
        nullable=False,
        server_default=sa.text("false")
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_deleted')
    op.drop_column('cart', 'grand_total')
    # ### end Alembic commands ###
