"""added one more coloum in cart item (item_total)

Revision ID: c95a9bfad477
Revises: 392c3723879f
Create Date: 2026-05-31 15:49:43.327081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95a9bfad477'
down_revision: Union[str, Sequence[str], None] = '392c3723879f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('item_total', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'item_total')
    # ### end Alembic commands ###
